---
Name: nswdpc-taggable-notifications
---
NSWDPC\Messaging\Taggable\ProjectTags:
  tag: ''
  tag_limit: 0
  tag_email_header_name: ''
  tag_email_header_serialisation: 'csv'
  tag_email_header_value_delimiter: ','
---
Name: nswdpc-taggable-email
---
# Note: set the Email configuration at the project level
---
Name: nswdpc-taggable-notifications-userforms
Only:
  moduleexists: 'silverstripe/userforms'
---
SilverStripe\UserForms\Control\UserDefinedFormController:
  extensions:
    - 'NSWDPC\Messaging\Taggable\UserDefinedFormControllerExtension'
SilverStripe\UserForms\Model\Recipient\EmailRecipient:
  extensions:
    - 'NSWDPC\Messaging\Taggable\UserFormEmailRecipientExtension'
SilverStripe\Taxonomy\TaxonomyTerm:
  extensions:
    - 'NSWDPC\Messaging\Taggable\UserFormEmailTagsExtension'
